---
deployment:
  tasks:
    - export NODE_ENV=production
    - /opt/cpanel/ea-nodejs18/bin/npm install
    - /opt/cpanel/ea-nodejs18/bin/npm run build
    - rsync -av --delete dist/ /home/zoes1nyqb4m0/public_html/
